---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nutanix-csi-snapshot
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nutanix-csi-snapshot
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nutanix-helm-releases
        namespace: ${releaseNamespace}
      version: 6.3.3
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: ntnx-system
  releaseName: nutanix-csi-snapshot
  valuesFrom:
    - kind: ConfigMap
      name: nutanix-csi-snapshot-6.3.3-defaults
    - kind: ConfigMap
      name: nutanix-csi-snapshot-overrides
      optional: true
