---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nutanix-csi-storage
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nutanix-csi-storage
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nutanix-helm-releases
        namespace: ${releaseNamespace}
      version: 3.2.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: ntnx-system
  releaseName: nutanix-csi-storage
  valuesFrom:
    - kind: ConfigMap
      name: nutanix-csi-storage-3.2.0-defaults
    - kind: ConfigMap
      name: nutanix-csi-storage-overrides
      optional: true
